name: test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'

env:
  BRANCH: ${{ github.head_ref }}

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Set documentation url status (PR)
        uses: ouzi-dev/commit-status-updater@v1.0.4
        with:
          name: 'documemtation'
          url: https://github.com/migom1030/github-actions
          status: success
        if: github.ref != 'refs/heads/main'

      - name: Configure sysctl limits
        run: |
          sudo swapoff -a
          sudo sysctl -w vm.swappiness=1
          sudo sysctl -w fs.file-max=262144
          sudo sysctl -w vm.max_map_count=262144
      
      - uses: getong/elasticsearch-action@v1.2
        with:
          elasticsearch version: '7.6.1'
          host port: 9200
          container port: 9200
          host node port: 9300
          node port: 9300
          discovery type: 'single-node'
      